dist: xenial
language: node_js
node_js: node

cache:
  npm: true
  directories:
    - public

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-pip
  - sudo -H pip3 install --upgrade pip

script:
  - npm run build

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

